name: Publish VS Code Extension

on:
  push:
    tags:
      - "v*"
    

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Get version from GitHub tag
        id: get_version
        run: |
          # 例: v1.2.3 → 1.2.3 に変換
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set version in package.json
        run: |
          jq --arg version "${{ steps.get_version.outputs.version }}" '.version = $version' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: |
          vsce publish ${{ steps.get_version.outputs.version }} -p "$VSCE_PAT"
